DjangoCallanProject/DjangoCallanProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('callanapp.urls')),  # Включаем URL-пути из вашего приложения
    path('users/', include('usersapp.urls',  namespace='users')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

DjangoCallanProject/callanapp/urls.py
from django.urls import path, include
from callanapp import views
from .views import IndexView
from django.conf import settings
from django.conf.urls.static import static
from .views import Dictation_to_text, WordQuiz, WordView, DeleteAudioFileView, ReadBook, SearchAudioDictations, Contact, ReplyEmailView, YouTubeDataFetcher, YouTubeDataList
from django.contrib import admin

admin.autodiscover()

urlpatterns = [
    path('', IndexView.as_view(), name='index'),  # Главная страница
    path('dictation_to_text/', Dictation_to_text.as_view(), name='dictation_to_text'),  # URL-маршрут для преобразования текста в аудио
    path('convert_and_play/', Dictation_to_text.convert_and_play, name='convert_and_play'),  # URL-маршрут для преобразования текста и проигрывания
    path('delete_audio_file/', DeleteAudioFileView.as_view(), name='delete_audio_file'),  # URL-маршрут для удаления аудиофайла
    path('select_stage_word/', WordView.as_view(), name='select_stage_word'),  # URL-маршрут для выбора уровня слова
    path('word_quiz/', WordQuiz.as_view(), name='word_quiz'),  # URL-маршрут для викторины по словам
    path('audio_url/', Dictation_to_text.convert_and_play, name='audio_url'),  # URL-маршрут для получения аудио-URL
    path('read_student_book/', ReadBook.as_view(), name='read_student_book'),  # URL-маршрут для чтения книги студента
    path('dictation_stage/', SearchAudioDictations.as_view(), name='dictation_stage'),  # URL-маршрут для поиска аудио-диктантов
    path('search_audio_dictations/', SearchAudioDictations.search_audio_dictations, name='search_audio_dictations'),  # URL-маршрут для выполнения поиска аудио-диктантов
    path('contact/', Contact.as_view(), name='contact'),  # URL-маршрут для страницы контактов
    # path('admin/sentemail/<int:email_id>/reply/', ReplyEmailView.as_view(), name='admin_sentemail_reply'),  # URL-маршрут для ответа на электронное письмо из административной панели
    path('sentemail/<int:email_id>/reply/', ReplyEmailView.as_view(), name='admin_sentemail_reply'),  # URL-маршрут для ответа на электронное письмо
    path('youtube_videos/', YouTubeDataFetcher.as_view(), name='youtube_videos'), # URL-маршрут для видеофайлов
    path('list_of_video_files/', YouTubeDataList.as_view(), name='list_of_video_files'), # URL-маршрут для видеофайлов в виде списка
]

# Добавляем статические маршруты для обслуживания медиафайлов только в режиме DEBUG
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DjangoCallanProject/usersapp/urls.py
# DjangoCallanProject/usersapp/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from . import views
from django.conf import settings
from django.conf.urls.static import static
from .views import CustomAuthenticationView

app_name = 'usersapp'

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('login_face/', CustomAuthenticationView.as_view(), name='login_face'),

    path('receive_username/', CustomAuthenticationView.as_view(), name='receive_username'),  # URL-маршрут для передачи имени пользователя
    #path('receive_face/', CustomAuthenticationView.as_view(), name='receive_face'),# URL-маршрут для передачи фото
    path('receive_face/', views.receive_face , name='receive_face'),

    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.UserCreateView.as_view(), name='register'),
    path('profile/<int:pk>/', views.UserDetailView.as_view(), name='profile'),
    path('profile/', views.UserDetailView.as_view(), name='profile_no_pk'),
    path('update_token/', views.update_token, name='update_token'),
    path('update_token_ajax/', views.update_token_ajax),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DjangoCallanProject/callanapp/models.py
# models.py
from django.db import models
from usersapp.models import BlogUser

# Менеджер для фильтрации только активных объектов
class ActiveManager(models.Manager):
    def get_queryset(self):
        all_objects = super().get_queryset()
        return all_objects.filter(is_active=True)

# Базовая абстрактная модель для общих полей
class BaseModel(models.Model):
    title_text_user = models.CharField(max_length=20)
    text_user = models.TextField(null=True, blank=True)
    audio_dictation = models.FileField(upload_to='audio/')

    class Meta:
        abstract = True  # Абстрактная модель, не создает отдельной таблицы в базе данных

    def __str__(self):
        return self.title_text_user  # Строковое представление объекта

# Модель для аудиодиктантов, наследующаяся от BaseModel
class AudioDictation(BaseModel):
    stage = models.IntegerField()

    def __str__(self):
        return f'{self.stage} - {self.title_text_user} - {self.text_user} - {self.audio_dictation}'

# Модель для хранения слов
class Word(models.Model):
    LEVEL_CHOICES = [
        ('Stage 1', 'Stage 1'),
        ('Stage 2', 'Stage 2'),
        ('Stage 3', 'Stage 3'),
        ('Stage 4', 'Stage 4'),
        # Добавьте остальные уровни по мере необходимости
    ]

    russian_word = models.CharField(max_length=255)
    english_translation = models.CharField(max_length=255)
    level = models.CharField(max_length=10, choices=LEVEL_CHOICES)

    def __str__(self):
        return f'{self.russian_word} ({self.level})'

# Модель для хранения отправленных электронных писем
class SentEmail(models.Model):
    subject = models.CharField(max_length=255)
    body = models.TextField()
    sender = models.EmailField()
    recipient = models.EmailField()
    sent_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(BlogUser, on_delete=models.CASCADE, null=True, blank=True)


    def __str__(self):
        return self.subject

DjangoCallanProject/callanapp/forms.py
# callanapp/forms.py
from django import forms

# Форма для ввода текста и скорости для создания аудиофайла
class DictationForm(forms.Form):
    text = forms.CharField(widget=forms.Textarea(attrs={'rows': 5, 'cols': 80}), label='Your Text')
    speed_factor = forms.FloatField(label='Speed Factor', initial=1.0)


# Форма для контактов (получения сообщений)
class ContactForm(forms.Form):
    name = forms.CharField(label='Title')
    email = forms.EmailField(label='Email')
    message = forms.CharField(label='Message')

# Форма для отправки ответных сообщений
class ReplyEmailForm(forms.Form):
    subject = forms.CharField(max_length=200, label='Subject')
    body = forms.CharField(widget=forms.Textarea, label='Body')

DjangoCallanProject/callanapp/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect, redirect
from django.http import HttpResponseBadRequest
from django.views.decorators.csrf import csrf_exempt
from django.core.exceptions import ValidationError
from .management.commands.text_to_audio import Command
from .models import Word, AudioDictation, SentEmail
from django.conf import settings
from django.http import JsonResponse
from django.views import View
from .forms import ContactForm, ReplyEmailForm
from django.shortcuts import reverse
from django.core.mail import send_mail
from django.contrib.auth.decorators import login_required
import os
from django.utils.decorators import method_decorator
from django.contrib import messages
import logging
from googleapiclient.discovery import build
from google.oauth2 import service_account
from django.shortcuts import render
import json
from django.views.decorators.cache import cache_page
from django.core.exceptions import MultipleObjectsReturned






logger = logging.getLogger(__name__)




# Базовый класс для представлений с общими методами
class BaseView(View):
    template_name = ''

    @method_decorator(login_required)
    def get(self, request):
        """Обработка GET-запроса."""
        return render(request, self.template_name)


class IndexView(BaseView):
    template_name = 'callanapp/index.html'




class Dictation_to_text(BaseView):
    template_name = 'callanapp/dictation_to_text.html'


    @staticmethod
    @csrf_exempt
    def convert_and_play(request):
        """Конвертация текста в аудио и воспроизведение."""
        if request.method == 'POST':
            try:
                text = request.POST['text']
                speed_factor = float(request.POST['speed_factor'])
                command = Command()
                command.handle(text=text, speed_factor=speed_factor)

                # Путь к созданному аудиофайлу
                new_output_path = os.path.join(settings.MEDIA_ROOT, 'speed_changed.mp3')
                audio_url = request.build_absolute_uri(settings.MEDIA_URL + 'speed_changed.mp3')

                return JsonResponse({'status': 'success', 'audio_url': audio_url})
            except ValidationError as e:
                return JsonResponse({'status': 'error', 'message': str(e), 'code': e.code})
        return JsonResponse({'status': 'error', 'message': 'Недопустимый метод запроса'})


class SearchAudioDictations(BaseView):
    template_name = 'callanapp/dictation_stage.html'

    @staticmethod
    def search_audio_dictations(request):
        """Поиск аудиодиктантов."""
        try:
            stage = request.GET.get('stage')
            audio_dictations = SearchAudioDictations.get_audio_dictations(stage)
            result = SearchAudioDictations.get_audio_dictation_info(audio_dictations)
            return JsonResponse({'status': 'success', 'audio_dictations': result})
        except ValidationError as e:
            return JsonResponse({'status': 'error', 'message': str(e), 'code': e.code})

    @staticmethod
    def get_audio_dictations(stage):
        """Получение аудиодиктантов."""
        return AudioDictation.objects.filter(stage__exact=stage)

    @staticmethod
    def get_audio_dictation_info(audio_dictations):
        """Получение информации об аудиодиктантах."""
        result = []
        for audio_dictation in audio_dictations:
            audio_url = audio_dictation.audio_dictation.url
            result.append({
                'stage': audio_dictation.stage,
                'title_text_user': audio_dictation.title_text_user,
                'text_user': audio_dictation.text_user,
                'audio_url': audio_url,
            })
        return result

class DeleteAudioFileView(BaseView):
    def post(self, request):
        """Удаление аудиофайла."""
        try:
            file_name = 'speed_changed.mp3'
            self.delete_audio_file(file_name)
            return JsonResponse({'status': 'success'})
        except Exception as e:
            return JsonResponse({'status': 'error', 'message': str(e)})

    def delete_audio_file(self, file_name):
        """Удаление аудиофайла из хранилища Django."""
        file_path = os.path.join(settings.MEDIA_ROOT, file_name)
        os.remove(file_path)


class WordView(BaseView):
    template_name = 'callanapp/select_stage_word.html'

class WordQuiz(View):
    template_name = 'callanapp/quiz.html'

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.words = None
        #self.level_text = None

    def get(self, request):
        """Отображение викторины по словам."""
        level = request.GET.get('level')  # Получаем значение уровня из запроса

        # Преобразование численного значения в текстовый формат уровня
        self.level_text = f'Stage {level}' if level else None
        print('Уровень:', self.level_text)

        if level:
            self.words = Word.objects.filter(level=self.level_text)  # Фильтруем слова по выбранному уровню
        else:
            self.words = None  # Если уровень не выбран, обнуляем список слов

        context = {'level': self.level_text,
                   'words': self.words}
        total_count = len(context.get('words', []))
        request.session['total_count'] = total_count  # Сохраняем total_count в сессии


        return render(request, self.template_name, context)


    def post(self, request):
        total_count = request.session.get('total_count', 0)  # Получаем total_count из сессии


        """Обработка ответов пользователя в викторине по словам."""
        user_answers = request.POST  # Получаем ответы пользователя из POST-запроса

        user_answers_dict = {}

        # Создаем словарь ответов пользователя, исключая CSRF-токен
        for key in user_answers.keys():
            if key != 'csrfmiddlewaretoken':
                user_answers_dict[key] = user_answers.get(key)
        print(user_answers_dict)

        correct_count = 0
        correct_answers = []

        # Проходим по словарю ответов пользователя
        for russian_word, user_answer in user_answers_dict.items():
            try:
                # Получаем объект модели Word, используя русское слово в качестве фильтра
                word_obj_model = Word.objects.filter(russian_word=russian_word).first()
                # Получаем строковое представление объекта
                str_representation = str(word_obj_model)
                # Разбиваем строку по скобкам
                word, level = str_representation.split('(', 1)
                # Удаляем пробелы в конце слова
                word = word.strip()

                # Получаем правильный перевод слова из атрибута english_translation объекта модели Word
                correct_translation = word_obj_model.english_translation

                # Проверяем правильность ответа пользователя
                if user_answer.strip().lower() == correct_translation.lower():
                    # Если ответ правильный, увеличиваем счетчик правильных ответов
                    correct_count += 1

                # Добавляем информацию о слове в список правильных ответов
                correct_answers.append({
                    'russian_word': word,
                    'user_answer': user_answer,
                    'correct_translation': correct_translation
                })
            except Word.DoesNotExist:
                # Если слово не найдено в базе данных, обработайте это здесь
                pass

        # Подготавливаем контекст для передачи в шаблон
        context = {
            'correct_count': correct_count,
            'total_count': total_count,
            'correct_answers': correct_answers
        }

        print('correct_count:', correct_count)
        print('total_count:', total_count)

        # Возвращаем ответ с данными для шаблона
        return render(request, self.template_name, context)


class ReadBook(BaseView):
    template_name = 'callanapp/read_student_book.html'


class Contact(BaseView):
    template_name = 'callanapp/contact.html'

    def get(self, request):
        """Отображение формы контактов."""
        form = ContactForm()
        return render(request, self.template_name, context={'form': form})

    def post(self, request):
        """Обработка отправки формы контактов."""
        form = ContactForm(request.POST)
        if form.is_valid():
            name, message, email = self.extract_form_data(form)
            self.send_contact_email(message, email)
            return HttpResponseRedirect(reverse('index'))
        else:
            return render(request, self.template_name, context={'form': form})

    def extract_form_data(self, form):
        """Извлечение данных из формы контактов."""
        return form.cleaned_data['name'], form.cleaned_data['message'], form.cleaned_data['email']

    def send_contact_email(self, message, email):
        """Отправка уведомления о получении сообщения."""
        email_subject = 'Contact message'
        email_body = f'Your message: {message}\n\n\nYour message has been received. Thank you!'
        try:
            send_mail(
                email_subject,
                email_body,
                settings.DEFAULT_FROM_EMAIL,
                [email],
                fail_silently=False,
            )
            SentEmail.objects.create(
                subject=email_subject,
                body=email_body,
                sender=settings.DEFAULT_FROM_EMAIL,
                recipient=email,
            )
        except Exception as e:
            logger.error(f"Failed to send email: {e}")
        else:
            logger.info("Email sent successfully!")


class ReplyEmailView(BaseView):
    template_name = 'admin/reply_email.html'

    def get(self, request, email_id):
        """Обработка GET-запроса при ответе на электронное письмо."""
        email = self.get_sent_email_or_404(email_id)

DjangoCallanProject/callanapp/templates/base_templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <!-- Применение фильтра capitalize -->
    <title>{% block title %}{{"главная страница"}}{% endblock %}</title>
    <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
    <!-- Основные стили CSS (включая Bootstrap)-->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
</head>
<body>
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
        <div class="container px-4 px-lg-5">
            <a class="navbar-brand" href="{% block home_link %}{% url 'index' %}{% endblock %}"> <h2>Home page</h2></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                Menu
                <i class="fas fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ms-auto py-4 py-lg-0">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle px-lg-3 py-3 py-lg-4" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <h2>MENU</h2>
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <!-- Остальные пункты меню -->
                            <li><a class="dropdown-item" href="{% url 'index' %}">Home page</a></li>
                            <li><a class="dropdown-item" href="{% url 'dictation_stage' %}">Dictation stage</a></li>
                            <li><a class="dropdown-item" href="{% url 'dictation_to_text' %}">Dictation to text</a></li>
                            <li><a class="dropdown-item" href="{% url 'select_stage_word' %}">Word</a></li>
                            <li><a class="dropdown-item" href="{% url 'read_student_book' %}">Read Student’s Book</a></li>
                            <li><a class="dropdown-item" href="{% url 'youtube_videos' %}">Video Tutorials on YouTube</a></li>
                            <li><a class="dropdown-item" href="{% url 'contact' %}">Contact</a></li>
                            <!-- Остальные пункты меню -->
                            <li><a class="dropdown-item" href="{% url 'users:login' %}">Enter the site</a></li>
                            <li><a class="dropdown-item" href="{% url 'users:login_face' %}"></a></li>
                            <li><a class="dropdown-item" href="{% url 'users:register' %}">Registration</a></li>
                            <li><a class="dropdown-item" href="{% url 'users:profile_no_pk' %}">User profile</a></li>
                        </ul>
                    </li>
                </ul>
                <div class="nav-item">
                    {% if user.is_authenticated %}
                        <span class="red-text" style="font-weight: bold; color: green;">
                            Hello, <a href="{% url 'usersapp:profile' pk=user.pk %}">{{ user.username }}</a>
                            {% if user.face_image %}
                                <img src="{{ user.face_image.url }}" alt="{{ user.username }}" width="50" height="50">
                            {% endif %}
                            <form method="post" action="{% url 'users:logout' %}">
                                {% csrf_token %}
                                <button type="submit" class="nav-link px-lg-3 py-3 py-lg-4" style="border: 1px solid #ccc; background-color: #eee; cursor: pointer; padding: 10px 20px; text-decoration: none; color: #333;">Go out</button>
                            </form>
                        </span>
                    {% else %}
                        <span class="red-text" style="font-weight: bold; color: green;">
                            <a href="{% url 'users:login' %}">Enter</a>
                        </span>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>

    <div class="container px-4 px-lg-5">
        {% block content %}{% endblock %}
    </div>

    <footer class="border-top">
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <ul class="list-inline text-center">
                        <!-- Social icons -->
                    </ul>
                    <div class="small text-center text-muted fst-italic">Callan Method</div>
                    <div class="small text-center text-muted fst-italic">{{inform}}</div>
                </div>
            </div>
        </div>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% block scripts %}{% static 'js/scripts.js' %}{% endblock %}"></script>
</body>

</html>